### Q1.WRITE A FUNCTION THAT TAKES A VARIABLE AND SQUARE IT, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER"


In [1]:
def sq_num(x):
    return x ** 2

a = float(input("Enter a number: "))
result = sq_num(a)
print("The square is",result)

Enter a number: 7
The square is 49.0


### Q2.WRITE A FUNCTION THAT TAKES 2 VARIABLE AND OBTAIN THE SUMMATION AND MULTIPLICATION, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER (REPEAT USING LAMBDA EXPRESSIONS)


In [2]:

def calculation(x, y):
    add_num = x + y
    product_num = x * y
    return add_num, product_num

user_input1 = float(input("Enter the first number: "))
user_input2 = float(input("Enter the second number: "))

add_result, mul_result = calculation(user_input1, user_input2)
print("Sum :", add_result)
print("Product :" , mul_result)

Enter the first number: 6
Enter the second number: 9
Sum : 15.0
Product : 54.0


### Q3 Write a program which accept one number from user and return its factorial.

In [3]:


def Factorial(n):
          i=1
          while n>0:
                    i=i*n
                    n=n-1
          return i

x=(int(input("Enter the number")))
print("Factorial ",x,Factorial(x))

Enter the number5
Factorial  5 120


### Q4.DEVELOP A SCRIPT WHOSE ITEMS ARE SQUARES OF THE ORIGINAL LIST


In [5]:

def square_list(numbers):
    squared_list = [x ** 2 for x in numbers] #list comprehension
    return squared_list

original_list = [1, 2, 3, 4, 5]
squared_numbers = square_list(original_list)

print("Original List:", original_list)
print("Squared List:", squared_values)

Original List: [1, 2, 3, 4, 5]


NameError: name 'squared_values' is not defined

### Q5.WRITE A FUNCTION THAT SQUARES A VARIABLE AND THEN TEST THE FUNCTION USING A LIST OF INTEGER NUMBERS RANGING FROM -20 to 20


In [6]:


def square_num(x):
    return x ** 2

numbers = list(range(-20, 21))

for num in numbers:
    squared = square_number(num)
    print("The square of" ,{num}, "is", {squared})

NameError: name 'square_number' is not defined

### Q6.WRITE 3 FUNCTIONS THAT TAKE THE RADIUS OF A CIRCLE AND RETURN THE DIAMETER, AREA AND CIRCUMFERENCE, 
### TEST THE FUNCTION USING AN INPUT FROM A USER

In [7]:

import math

def calculate_diameter(rad):
    return 2 * rad

def calculate_area(rad):
    return math.pi * rad ** 2

def calculate_circumference(rad):
    return 2 * math.pi * rad

user_rad = float(input("Enter the radius of the circle: "))

diameter = calculate_diameter(user_rad)
area = calculate_area(user_rad)
circumference = calculate_circumference(user_rad)

print("Given radius " ,user_rad)
print(f"Diameter: " ,diameter)
print(f"Area: ",area)
print(f"Circumference: " , circumference)

Enter the radius of the circle: 4
Given radius  4.0
Diameter:  8.0
Area:  50.26548245743669
Circumference:  25.132741228718345


### Q7.WRITE A CODE THAT TAKES A RANGE FROM A USER (UPPER AND LOWER BOUND) AND RETURNS A LIST OF POSITIVE AND EVEN NUMBERS ONLY


In [8]:

def get_posi_even_numbers(lower, upper):
    posi_even_numbers = []
    for num in range(lower, upper + 1):
        if num > 0 and num % 2 == 0:
            posi_even_numbers.append(num)
    return posi_even_numbers

lower_bound = int(input("Enter the lower bound of the range: "))
upper_bound = int(input("Enter the upper bound of the range: "))

even_numbers_list = get_posi_even_numbers(lower_bound, upper_bound)
print("List of positive and even numbers:",even_numbers_list)

Enter the lower bound of the range: 3
Enter the upper bound of the range: 9
List of positive and even numbers: [4, 6, 8]


### Q8.USING FILTER AND LAMBDA EXPRESSION, WRITE A CODE THAT TAKES A LIST OF NUMBERS BELOW AND RETURNS EVEN NUMBERS ONLY


In [9]:

numbers = list(range(-20,20))
 
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print("Even numbers:", even_numbers)

Even numbers: [-20, -18, -16, -14, -12, -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [12]:
import numpy as np

def matrix_operations(matrix1, matrix2):
    addition = matrix1 + matrix2
    subtraction = matrix1 - matrix2
    transpose_M1 = np.transpose(matrix1)
    transpose_M2 = np.transpose(matrix2)
    product = matrix1 * matrix2
    dot_product = np.dot(matrix1, matrix2)
    
    return {
        'addition': addition,
        'subtraction': subtraction,
        'transpose1': transpose_M1,
        'transpose2': transpose_M2,
        'element_wise_product': product,
        'dot_product': dot_product
    }


matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

result = matrix_operations(matrix_a, matrix_b)

print("Addition:\n", result['addition'])
print("Subtraction:\n", result['subtraction'])
print("Transpose of Matrix 1:\n", result['transpose1'])
print("Transpose of Matrix 2:\n", result['transpose2'])
print("Element-wise Product:\n", result['element_wise_product'])
print("Dot Product:\n", result['dot_product'])

Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Transpose of Matrix 1:
 [[1 3]
 [2 4]]
Transpose of Matrix 2:
 [[5 7]
 [6 8]]
Element-wise Product:
 [[ 5 12]
 [21 32]]
Dot Product:
 [[19 22]
 [43 50]]


In [14]:
def sum(a=3, b=5):
    return a + b


user_input1 = input("Enter the first number : ")
user_input2 = input("Enter the second number : ")

# Use default values if no input is provided
if user_input1 == "":
    user_input1 = 3
if user_input2 == "":
    user_input2 = 5

result = sum(float(user_input1),float(user_input2))
print("The sum of:" ,user_input1 ,"and" ,user_input2, "is" ,result)

Enter the first number : 3
Enter the second number : 5
The sum of: 3 and 5 is 8.0


In [15]:
def check_numbers(min_value, max_value):
    filtered_numbers = []
    for num in range(min_value, max_value + 1):
        if num % 4 == 0 and num % 3 != 0:
            filtered_numbers.append(num)
    return filtered_numbers

min_range = int(input("Enter the minimum value : "))
max_range = int(input("Enter the maximum value : "))

divisible_numbers = check_numbers(min_range, max_range)
print("Numbers divisible by 4 but not multiples of 3:", divisible_numbers)

Enter the minimum value : 12
Enter the maximum value : 60
Numbers divisible by 4 but not multiples of 3: [16, 20, 28, 32, 40, 44, 52, 56]


### Q12.DEFINE AN ENGLISH TO FRENCH TRANSLATOR FUNCTION THAT TAKES AN INPUT FROM A USER AND RETURNS THE TRANSLATION, USE ANY 5 KNOWN WORDS


In [11]:


def english_to_french_translator(word):
    translations = {
        "go": "Aller",
        "apple": "pomme",
        "come": "Viens",
        "parrot": "perroquet",
        "Car": "Voiture"
    }

    translated_word = translations.get(word.lower(), "word not found in dictionary")
    return translated_word

user_input = input("Enter an English word: ")
translated_word = english_to_french_translator(user_input)

print("The translation of",user_input, "in French is: ",translated_word)

Enter an English word: come
The translation of come in French is:  Viens
